experiment_name: "anything_depth"
output_dir: ""
train_img_dir: ""
train_depth_dir: ""
train_label_dir: ""
val_img_dir: ""
val_depth_dir: ""
val_label_dir: ""
test_img_dir: ""
test_depth_dir: ""
test_label_dir: ""
depth_checkpoint: ""
batch_size: 16
num_workers: 16
learning_rate: 0.001
lr_decay: 0.0005
num_epochs: 100
device: "cuda"
model_type: "depth"
fuse_layer: 15
val_every: 1
normalization: False