dataset_name: "anythingv2"
base_dir: "/home/escorpiao/workspace/depth-anything-dataset/data"
train_img_dir: "/image_splits/train/images"
train_depth_dir: "/Depth_anything_v2/train/depth"
train_label_dir: "/image_splits/train/labels"
batch_size: 32
num_workers: 32
learning_rate: 0.01
num_epochs: 300
device: "cuda"
model_type: "rgbd"
fuse_layer: 15