dataset_name: "anythingv2_newsplit"
base_dir: "/home/gkmo/workspace/data"
train_img_dir: "/home/gustavo/workstation/depth_estimation/data/new_splits/train/images/"
train_depth_dir: "/home/gustavo/workstation/depth_estimation/data/new_anything_split/train/"
train_label_dir: "/home/gustavo/workstation/depth_estimation/data/new_splits/train/labels/"
val_img_dir: "/home/gustavo/workstation/depth_estimation/data/new_splits/val/images/"
val_depth_dir: "/home/gustavo/workstation/depth_estimation/data/new_anything_split/val/"
val_label_dir: "/home/gustavo/workstation/depth_estimation/data/new_splits/val/labels/"
test_img_dir: "/home/gustavo/workstation/depth_estimation/data/new_splits/test/images/"
test_depth_dir: "/home/gustavo/workstation/depth_estimation/data/new_anything_split/test/"
test_label_dir: "/home/gustavo/workstation/depth_estimation/data/new_splits/test/labels/"
batch_size: 16
num_workers: 16
learning_rate: 0.01
num_epochs: 5
device: "cuda"
model_type: "rgbd"
fuse_layer: 15
val_every: 1