dataset_name: "anythingv2"
base_dir: "/home/gkmo/workspace/data"
train_img_dir: "/image_splits/train/images"
train_depth_dir: "/Depth_anything_v2/train/depth"
train_label_dir: "/image_splits/train/labels"
batch_size: 16
num_workers: 16
learning_rate: 0.01
num_epochs: 500
device: "cuda"
model_type: "rgbd"
fuse_layer: 15