dataset_name: "anythingv2_newsplit"
base_dir: "/home/escorpiao/workspace/depth-anything-dataset/data/new_splits"
train_img_dir: "/home/escorpiao/workspace/depth-obj-detection/data/new_splits/train/images"
train_label_dir: "/home/escorpiao/workspace/depth-obj-detection/data/new_splits/train/labels"
val_img_dir: "/home/escorpiao/workspace/depth-obj-detection/data/new_splits/val/images"
val_label_dir: "/home/escorpiao/workspace/depth-obj-detection/data/new_splits/val/labels"
test_img_dir: "/home/escorpiao/workspace/depth-obj-detection/data/new_splits/test/images"
test_label_dir: "/home/escorpiao/workspace/depth-obj-detection/data/new_splits/test/labels"
train_depth_dir: "/home/escorpiao/workspace/depth-obj-detection/data/new_anything_split/train"
val_depth_dir: "/home/escorpiao/workspace/depth-obj-detection/data/new_anything_split/val"
test_depth_dir: "/home/escorpiao/workspace/depth-obj-detection/data/new_anything_split/test"
batch_size: 16
num_workers: 16
learning_rate: 0.01
num_epochs: 300
device: "cuda"
model_type: "rgb"
fuse_layer: 15
val_every: 1